### ISSUE TITLE
SearchReadsExample1 error

### ISSUE THREAD

**Issue by tcfuji** [googlegenomics/spark-examples#65]
Getting the following error: 
```
tcf@hs-ghfs-nn:~$ export SPARK_CLASSPATH=googlegenomics-spark-examples-assembly-1.0.jar
tcf@hs-ghfs-nn:~$ spark-class com.google.cloud.genomics.spark.examples.SearchReadsExample1 --client-secrets client_secrets.json --spark-master spark://hs-ghfs-nn:7077 --jar-path googlegenomics-spark-examples-assembly-1.0.jar
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/03/26 02:43:15 WARN SparkConf: In Spark 1.0 and later spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone and LOCAL_DIRS in YARN).
15/03/26 02:43:15 WARN SparkConf:
SPARK_JAVA_OPTS was detected (set to '-Dspark.local.dir=/hadoop/spark/tmp -Dspark.executor.memory=12060m ').
This is deprecated in Spark 1.0+.

Please instead use:
 - ./spark-submit with conf/spark-defaults.conf to set defaults for an application
 - ./spark-submit with --driver-java-options to set -X options for a driver
 - spark.executor.extraJavaOptions to set -X options for executors
 - SPARK_DAEMON_JAVA_OPTS to set java options for standalone daemons (master or worker)

15/03/26 02:43:15 WARN SparkConf: Setting 'spark.executor.extraJavaOptions' to '-Dspark.local.dir=/hadoop/spark/tmp -Dspark.executor.memory=12060m ' as a work-around.
15/03/26 02:43:15 WARN SparkConf: Setting 'spark.driver.extraJavaOptions' to '-Dspark.local.dir=/hadoop/spark/tmp -Dspark.executor.memory=12060m ' as a work-around.
15/03/26 02:43:15 WARN SparkConf:
SPARK_CLASSPATH was detected (set to 'googlegenomics-spark-examples-assembly-1.0.jar:/home/hadoop/hadoop-install/lib/gcs-connector-1.2.6-hadoop1.jar').
This is deprecated in Spark 1.0+.

Please instead use:
 - ./spark-submit with --driver-class-path to augment the driver classpath
 - spark.executor.extraClassPath to augment the executor classpath

15/03/26 02:43:15 WARN SparkConf: Setting 'spark.executor.extraClassPath' to 'googlegenomics-spark-examples-assembly-1.0.jar:/home/hadoop/hadoop-install/lib/gcs-connector-1.2.6-hadoop1.jar' as a work-around.
15/03/26 02:43:15 WARN SparkConf: Setting 'spark.driver.extraClassPath' to 'googlegenomics-spark-examples-assembly-1.0.jar:/home/hadoop/hadoop-install/lib/gcs-connector-1.2.6-hadoop1.jar' as a work-around.
15/03/26 02:43:15 INFO SecurityManager: Changing view acls to: tcf
15/03/26 02:43:15 INFO SecurityManager: Changing modify acls to: tcf
15/03/26 02:43:15 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(tcf); users with modify permissions: Set(tcf)
15/03/26 02:43:16 INFO Slf4jLogger: Slf4jLogger started
15/03/26 02:43:16 INFO Remoting: Starting remoting
15/03/26 02:43:16 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@hs-ghfs-nn.c.secret-primacy-89223.internal:37326]
15/03/26 02:43:16 INFO Remoting: Remoting now listens on addresses: [akka.tcp://sparkDriver@hs-ghfs-nn.c.secret-primacy-89223.internal:37326]
15/03/26 02:43:16 INFO Utils: Successfully started service 'sparkDriver' on port 37326.
15/03/26 02:43:16 INFO SparkEnv: Registering MapOutputTracker
15/03/26 02:43:16 INFO SparkEnv: Registering BlockManagerMaster
15/03/26 02:43:16 INFO DiskBlockManager: Created local directory at /hadoop/spark/tmp/spark-local-20150326024316-4317
15/03/26 02:43:16 INFO Utils: Successfully started service 'Connection manager for block manager' on port 33734.
15/03/26 02:43:16 INFO ConnectionManager: Bound socket to port 33734 with id = ConnectionManagerId(hs-ghfs-nn.c.secret-primacy-89223.internal,33734)
15/03/26 02:43:16 INFO MemoryStore: MemoryStore started with capacity 265.4 MB
15/03/26 02:43:16 INFO BlockManagerMaster: Trying to register BlockManager
15/03/26 02:43:16 INFO BlockManagerMasterActor: Registering block manager hs-ghfs-nn.c.secret-primacy-89223.internal:33734 with 265.4 MB RAM, BlockManagerId(<driver>, hs-ghfs-nn.c.secret-primacy-89223.internal, 33734, 0)
15/03/26 02:43:16 INFO BlockManagerMaster: Registered BlockManager
15/03/26 02:43:16 INFO HttpFileServer: HTTP File server directory is /tmp/spark-f4da190d-82c6-40d2-b9b6-16dfd617253e
15/03/26 02:43:16 INFO HttpServer: Starting HTTP Server
15/03/26 02:43:16 INFO Utils: Successfully started service 'HTTP file server' on port 33768.
15/03/26 02:43:16 ERROR MetricsSystem: Sink class org.apache.spark.metrics.sink.MetricsServlet cannot be instantialized
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:140)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:134)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
	at org.apache.spark.metrics.MetricsSystem.registerSinks(MetricsSystem.scala:134)
	at org.apache.spark.metrics.MetricsSystem.<init>(MetricsSystem.scala:84)
	at org.apache.spark.metrics.MetricsSystem$.createMetricsSystem(MetricsSystem.scala:171)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:251)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:204)
	at com.google.cloud.genomics.spark.examples.GenomicsConf.newSparkContext(GenomicsConf.scala:57)
	at com.google.cloud.genomics.spark.examples.SearchReadsExample1$.main(SearchReadsExample.scala:80)
	at com.google.cloud.genomics.spark.examples.SearchReadsExample1.main(SearchReadsExample.scala)
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:445)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:366)
	at org.apache.spark.metrics.sink.MetricsServlet.<init>(MetricsServlet.scala:45)
	... 19 more
15/03/26 02:43:16 INFO Utils: Successfully started service 'SparkUI' on port 4040.
15/03/26 02:43:16 INFO SparkUI: Started SparkUI at http://hs-ghfs-nn.c.secret-primacy-89223.internal:4040
15/03/26 02:43:17 INFO SparkContext: Added JAR googlegenomics-spark-examples-assembly-1.0.jar at http://10.240.113.211:33768/jars/googlegenomics-spark-examples-assembly-1.0.jar with timestamp 1427337797646
15/03/26 02:43:17 INFO AppClient$ClientActor: Connecting to master spark://hs-ghfs-nn:7077...
15/03/26 02:43:17 INFO SparkDeploySchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
Please open the following address in your browser:
  https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=128122737342-ddjjjtaefpeopa3dfhrihviboioa5b87.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=https://www.googleapis.com/auth/genomics%20https://www.googleapis.com/auth/bigquery%20https://www.googleapis.com/auth/devstorage.read_write%20https://www.googleapis.com/auth/genomics.readonly
Please enter code: 4/aCQ8wcXRw-f4MfGv-h4CJE45B5RA47cCTqgNn61PgiA.Urn9nOz59rQZgtL038sCVnuLQ-2nmAI
                                                                                    v
CTGCTGCTTGAAAATGGATTGTGCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGAGCCAAGGCCTACAGAT(02) TTTGATCCCTTCCCTA
      CTTGAAAATGGATTGTGCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(43) TTTGATCCCTTCTCTATCCCAT
        TGAAAATGGATTGTGCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(47) TTTGATCCCTTCTCTATCCCATTC
              TGGATTGTGCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(39) TTTGATCCCTTCTCTATCCCATTCTATCAA
                         GCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACA(40) GATTTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCA
                                      GGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACA(42) GATTTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCT
                                       AATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(43) TTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGA
                                         ATATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(40) TTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGTAG
                                                                           GCCTACAGAT(38) TTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGTAGCATTATGACAATGTCACTCTGCAGCTTCAAATAT
                                                                                CAGAT(37) TTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGTAGCATTATGACAATGTCACTCTGCAGCTTCAAATATTCAGG
                                                                                   TA(02) TACCACCTAGTCTTCTTGACCAGAGGCTCACAGATTTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGTAGCATTATG
                                                                                    ^
15/03/26 02:43:44 ERROR ConnectionManager: Corresponding SendingConnection to ConnectionManagerId(hs-ghfs-dn-1.c.secret-primacy-89223.internal,39574) not found
15/03/26 02:43:45 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
15/03/26 02:43:45 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
```

**Comment by pgrosu** [comment]
Hi Ted,

I unfortunately don't have GCE connection to test and troubleshoot - though it would be nice to - but it looks like the Hadoop version that's on GCE uses a lower version of Jackson than 2.3.0, where this method is found, since it's caused by the following:

```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:445)
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:366)
    at org.apache.spark.metrics.sink.MetricsServlet.<init>(MetricsServlet.scala:45)
    ... 19 more
```

In any case the MetricsServlet sink - where this error initiates - is only for monitoring and should not hold up the running of the example.  For more information regarding MetricServlet, below is a link:

https://docs.sigmoidanalytics.com/index.php/Monitoring_and_Instrumentation

So as you notice at the end, the results still complete successfully based on the expected result you generate:

```
                                                                                    v
CTGCTGCTTGAAAATGGATTGTGCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGAGCCAAGGCCTACAGAT(02) TTTGATCCCTTCCCTA
      CTTGAAAATGGATTGTGCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(43) TTTGATCCCTTCTCTATCCCAT
        TGAAAATGGATTGTGCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(47) TTTGATCCCTTCTCTATCCCATTC
              TGGATTGTGCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(39) TTTGATCCCTTCTCTATCCCATTCTATCAA
                         GCGTAAAGACGGAGGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACA(40) GATTTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCA
                                      GGGTAATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACA(42) GATTTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCT
                                       AATTATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(43) TTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGA
                                         ATATAGATATACCACCTAGTCTTCTTGATCCGAGGCCTACAGAT(40) TTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGTAG
                                                                           GCCTACAGAT(38) TTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGTAGCATTATGACAATGTCACTCTGCAGCTTCAAATAT
                                                                                CAGAT(37) TTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGTAGCATTATGACAATGTCACTCTGCAGCTTCAAATATTCAGG
                                                                                   TA(02) TACCACCTAGTCTTCTTGACCAGAGGCTCACAGATTTTGATCCCTTCTCTATCCCATTCTATCAACAATGTCAGAGTGATCCTTCTAAGTAGCATTATG
                                                                                    ^
```

Hope it helps,
Paul

**Comment by tcfuji** [comment]
Thanks.
