### ISSUE TITLE
NullPointerException for 2-way PCA on PGP data

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/spark-examples#75]
Following the instructions here http://googlegenomics.readthedocs.org/en/latest/use_cases/compute_principal_coordinate_analysis/2-way-pca.html but just replacing the Platinum Genomes dataset id (3049512673186936334) with the [PGP dataset](http://googlegenomics.readthedocs.org/en/latest/use_cases/discover_public_data/pgp_public_data.html) id (9170389916365079788) results in a NullPointerException.  It works fine when I switch it back to the [Platinum Genomes dataset](http://googlegenomics.readthedocs.org/en/latest/use_cases/discover_public_data/platinum_genomes.html).

```
time spark-submit --class com.google.cloud.genomics.spark.examples.VariantsPcaDriver  \
  --conf spark.shuffle.spill=true   --master spark://hadoop-m:7077 \
  googlegenomics-spark-examples-assembly-1.0.jar   --client-secrets client_secrets.json \
  --variant-set-id 10473108253681171589 9170389916365079788 \
  --references 17:41196311:41277499 chr17:41196311:41277499 \
  --output-path pgp-two-way-brca1-pca.tsv
```

```
java.lang.NullPointerException
        at com.google.common.hash.AbstractHasher.putString(AbstractHasher.java:47)
        at com.google.cloud.genomics.spark.examples.VariantsPcaDriver$.getVariantKey(VariantsPca.scala:72)
        at com.google.cloud.genomics.spark.examples.VariantsPcaDriver$$anonfun$6$$anonfun$apply$6.apply(VariantsPca.scala:119)
        at com.google.cloud.genomics.spark.examples.VariantsPcaDriver$$anonfun$6$$anonfun$apply$6.apply(VariantsPca.scala:118)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at org.apache.spark.util.collection.ExternalSorter.spillToPartitionFiles(ExternalSorter.scala:371)
        at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:211)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by deflaux** [comment]
Running with `--debug-datasets` we see that there are some null values for reference
```
17: (41196407, 41196821) ref== alt=
17: (41196407, 41196407) ref=null alt=G
15/09/04 18:35:08 ERROR executor.Executor: Exception in task 1.0 in stage 0.0 (TID 1)
java.lang.NullPointerException
        at com.google.common.hash.AbstractHasher.putString(AbstractHasher.java:47)
        at com.google.cloud.genomics.spark.examples.VariantsPcaDriver$.getVariantKey(VariantsPca.scala:72)
```
